# Generated by Django 6.0.7 on 2026-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0002_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='PK-000', max_length=20),
        ),
    ]
