# Generated by Django 6.0.7 on 2026-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_system', '0003_flight_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
